# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: ru
permalink: /:title:output_ext
title: Pressfeed
email: sales@pressfeed.ru
phone: +7 (495) 120-80-19
description: >- # this means to ignore newlines until "baseurl:"
  Первый в России сервис журналистских запросов. Помогаем журналистам быстро получать фактуру для статей. А экспертам и пиарщикам — упоминания в СМИ
#baseurl: /pf-static # the subpath of your site, e.g. /blog
#url: https://fkolesnik.github.io # the base hostname & protocol for your site, e.g. http://example.com
telegram_link:  https://t-do.ru/pressfeed
vk_link:  https://vk.com/prsfd
facebook_link:  https://www.facebook.com/prsfd

# Build settings
destination: ../static

markdown: kramdown

collections:
  cases:
    output: true

defaults:
  - scope:
      path: ""
      type: "cases"
    values:
      layout: "case"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
