---
new_page_extension: md
auto_deploy: true
admin_path: ".forestry"
webhook_url: 
sections:
- type: directory
  path: _podcasts
  label: Подкасты
  create: all
  match: "**/*"
- type: directory
  path: _cases
  label: Кейсы
  create: all
  match: "**/*"
- type: directory
  path: _data/testimonials
  label: Отзывы
  create: all
  match: "**/*"
upload_dir: assets/uploads
public_path: "../assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
